apiVersion: apps/v1
kind: Deployment
metadata:
  name: kunal1010/prtimage
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kunal1010/prtimage
  template:
    metadata:
      labels:
        app: kunal1010/prtimage
    spec:
      containers:
        - name: kunal1010/prtimage-container
          image: kunal1010/prtimage
          ports:
            - containerPort: 80
